FROM python:3.11
WORKDIR /app
COPY ai-service/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ai-service/ .
RUN mkdir -p /app/models
EXPOSE 8001
CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8001"]
