
[alembic]
script_location = alembic
sqlalchemy.url = postgresql+asyncpg://crm_user:GVvMAwptKlakh3Uz9fMvlaCB66JsugMu@dpg-d8tqdfv7f7vs73ffg0tg-a.oregon-postgres.render.com:5432/ai_crm_m70n

[loggers]
keys = root,sqlalchemy,alembic

[logger_alembic]
level = INFO
handlers =
qualname = alembic
