FROM python:3.12
WORKDIR /app
COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .
EXPOSE 10000
CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "10000"]
